name: phone_input
description: This package is designed to simplify the process of capturing phone numbers from users.
version: 1.0.0
homepage: https://github.com/LanarsInc/phone_input

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.7
  intl: ">=0.17.0 <=1.0.0"
  diacritic: ^0.1.3
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/svg/
flutter_intl:
  enabled: true
