name: phone_input
description: This package is designed to simplify the process of capturing phone numbers from users.
version: 0.0.1
homepage: https://github.com/LanarsInc/phone_form_field

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  flutter_svg: ^2.0.7
  intl: ">=0.17.0 <=1.0.0"
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/svg/
